# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='users.proto',
  package='users',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0busers.proto\x12\x05users\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"2\n\tUserReply\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x12\n\nuser_email\x18\x02 \x01(\t\"\x1d\n\rUserPetsReply\x12\x0c\n\x04pets\x18\x01 \x03(\t2u\n\x05Users\x12\x31\n\x07GetUser\x12\x12.users.UserRequest\x1a\x10.users.UserReply\"\x00\x12\x39\n\x0bGetUSerPets\x12\x12.users.UserRequest\x1a\x14.users.UserPetsReply\"\x00\x62\x06proto3')
)




_USERREQUEST = _descriptor.Descriptor(
  name='UserRequest',
  full_name='users.UserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='users.UserRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=52,
)


_USERREPLY = _descriptor.Descriptor(
  name='UserReply',
  full_name='users.UserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='users.UserReply.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_email', full_name='users.UserReply.user_email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=104,
)


_USERPETSREPLY = _descriptor.Descriptor(
  name='UserPetsReply',
  full_name='users.UserPetsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pets', full_name='users.UserPetsReply.pets', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserReply'] = _USERREPLY
DESCRIPTOR.message_types_by_name['UserPetsReply'] = _USERPETSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERREQUEST,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserRequest)
  ))
_sym_db.RegisterMessage(UserRequest)

UserReply = _reflection.GeneratedProtocolMessageType('UserReply', (_message.Message,), dict(
  DESCRIPTOR = _USERREPLY,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserReply)
  ))
_sym_db.RegisterMessage(UserReply)

UserPetsReply = _reflection.GeneratedProtocolMessageType('UserPetsReply', (_message.Message,), dict(
  DESCRIPTOR = _USERPETSREPLY,
  __module__ = 'users_pb2'
  # @@protoc_insertion_point(class_scope:users.UserPetsReply)
  ))
_sym_db.RegisterMessage(UserPetsReply)



_USERS = _descriptor.ServiceDescriptor(
  name='Users',
  full_name='users.Users',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUser',
    full_name='users.Users.GetUser',
    index=0,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetUSerPets',
    full_name='users.Users.GetUSerPets',
    index=1,
    containing_service=None,
    input_type=_USERREQUEST,
    output_type=_USERPETSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERS)

DESCRIPTOR.services_by_name['Users'] = _USERS

# @@protoc_insertion_point(module_scope)
