# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import users_pb2 as users__pb2


class UsersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUser = channel.unary_unary(
        '/users.Users/GetUser',
        request_serializer=users__pb2.UserRequest.SerializeToString,
        response_deserializer=users__pb2.UserReply.FromString,
        )
    self.GetUserPets = channel.unary_unary(
        '/users.Users/GetUserPets',
        request_serializer=users__pb2.UserRequest.SerializeToString,
        response_deserializer=users__pb2.UserPetsReply.FromString,
        )


class UsersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserPets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UsersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=users__pb2.UserRequest.FromString,
          response_serializer=users__pb2.UserReply.SerializeToString,
      ),
      'GetUserPets': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserPets,
          request_deserializer=users__pb2.UserRequest.FromString,
          response_serializer=users__pb2.UserPetsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'users.Users', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
