# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pets_pb2 as pets__pb2


class PetsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPets = channel.unary_unary(
        '/pets.Pets/GetPets',
        request_serializer=pets__pb2.PetsRequest.SerializeToString,
        response_deserializer=pets__pb2.PetsReply.FromString,
        )


class PetsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PetsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPets': grpc.unary_unary_rpc_method_handler(
          servicer.GetPets,
          request_deserializer=pets__pb2.PetsRequest.FromString,
          response_serializer=pets__pb2.PetsReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pets.Pets', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
