# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pets.proto',
  package='pets',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\npets.proto\x12\x04pets\".\n\x0bPetsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0e\n\x06pet_id\x18\x02 \x01(\x05\"P\n\tPetsReply\x12\x14\n\x0cpets_message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0c\n\x04pets\x18\x03 \x03(\t\x12\x10\n\x08pet_name\x18\x04 \x01(\t27\n\x04Pets\x12/\n\x07GetPets\x12\x11.pets.PetsRequest\x1a\x0f.pets.PetsReply\"\x00\x62\x06proto3')
)




_PETSREQUEST = _descriptor.Descriptor(
  name='PetsRequest',
  full_name='pets.PetsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='pets.PetsRequest.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pet_id', full_name='pets.PetsRequest.pet_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=66,
)


_PETSREPLY = _descriptor.Descriptor(
  name='PetsReply',
  full_name='pets.PetsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pets_message', full_name='pets.PetsReply.pets_message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='pets.PetsReply.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pets', full_name='pets.PetsReply.pets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pet_name', full_name='pets.PetsReply.pet_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=148,
)

DESCRIPTOR.message_types_by_name['PetsRequest'] = _PETSREQUEST
DESCRIPTOR.message_types_by_name['PetsReply'] = _PETSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PetsRequest = _reflection.GeneratedProtocolMessageType('PetsRequest', (_message.Message,), dict(
  DESCRIPTOR = _PETSREQUEST,
  __module__ = 'pets_pb2'
  # @@protoc_insertion_point(class_scope:pets.PetsRequest)
  ))
_sym_db.RegisterMessage(PetsRequest)

PetsReply = _reflection.GeneratedProtocolMessageType('PetsReply', (_message.Message,), dict(
  DESCRIPTOR = _PETSREPLY,
  __module__ = 'pets_pb2'
  # @@protoc_insertion_point(class_scope:pets.PetsReply)
  ))
_sym_db.RegisterMessage(PetsReply)



_PETS = _descriptor.ServiceDescriptor(
  name='Pets',
  full_name='pets.Pets',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=150,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPets',
    full_name='pets.Pets.GetPets',
    index=0,
    containing_service=None,
    input_type=_PETSREQUEST,
    output_type=_PETSREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PETS)

DESCRIPTOR.services_by_name['Pets'] = _PETS

# @@protoc_insertion_point(module_scope)
